import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {

  const [slow, setSlow] = useState([]);
  const [fast, setFast] = useState([]);
  

  useEffect(() => {
    setSlow([...document.getElementsByClassName(`${styles.slow}`)]);
    setFast([...document.getElementsByClassName(`${styles.slow}`)]);

  }, [])

  useEffect(() => {
    handleMouseMove;
  }, [slow, fast])

  const handleMouseMove = (e) => {
    let normalizedPosition = e.pageX / (window.innerWidth / 2) -1;
    let speedSlow = 100 * normalizedPosition;
    let speedFast = 200 * normalizedPosition;
    // console.log(speedSlow, speedFast, normalizedPosition, slow);

    slow.forEach((element) => {
      element.style.transform = `translate(${speedSlow}px)`;
    });

    fast.forEach((element) => {
      element.style.transform = `translate(${speedFast}px)`;
    });
  }

  
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.logo_wrapper}>
        {/* logo animation */}
        <div className={styles.line}>
          <div className={styles.left}>
            <div className={styles.content}>
              <span className={`${styles.span} ${styles.slow}`}>THINK</span>
            </div>
          </div>
          <div className={styles.right}>
            <div className={styles.content}>
              <span className={`${styles.span} ${styles.slow}`}>ONCE</span>
            </div>
          </div>
        </div>
        <div className={styles.line}>
          <div className={styles.left}>
            <div className={styles.content}>
              <span className={`${styles.span} ${styles.slow}`}>THINK</span>
            </div>
          </div>
          <div className={styles.right}>
            <div className={styles.content}>
              <span className={`${styles.span} ${styles.slow}`}>TWICE</span>
            </div>
          </div>
        </div>
        <div className={styles.line}>
          <div className={styles.left}>
            <div className={styles.content}>
              <span className={`${styles.span} ${styles.fast}`}>THINK</span>
            </div>
          </div>
          <div className={styles.right}>
            <div className={styles.content}>
              <span className={`${styles.span} ${styles.fast}`}>DELICIOUS</span>
            </div>
          </div>
        </div>
        {/* logo animation */}
      </div>
    </div>
  )
}
