import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.logo_wrapper}>
        {/* logo animation */}
        <div className={styles.line}>
          <div className={styles.right}>
            <div className={styles.content}>
              <span>THINK</span>
            </div>
          </div>
          <div className={styles.right}>
            <div className={styles.content}>
              <span>ONCE</span>
            </div>
          </div>
        </div>
        <div className={styles.line}>
          <div className={styles.left}>
            <div className={styles.content}>
              <span>THINK</span>
            </div>
          </div>
          <div className={styles.right}>
            <div className={styles.content}>
              <span>TWICE</span>
            </div>
          </div>
        </div>
        <div className={styles.line}>
          <div className={styles.left}>
            <div className={styles.content}>
              <span>THINK</span>
            </div>
          </div>
          <div className={styles.right}>
            <div className={styles.content}>
              <span>DELICIOUS</span>
            </div>
          </div>
        </div>
        {/* logo animation */}
      </div>
    </div>
  )
}
